// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGn07ehAPPdAb0HXiPQa4yQig3zdJx1xQ',
    appId: '1:491367868510:web:d9dbdccd5358a4c08c6ccf',
    messagingSenderId: '491367868510',
    projectId: 'todo-app-df164',
    authDomain: 'todo-app-df164.firebaseapp.com',
    storageBucket: 'todo-app-df164.appspot.com',
    measurementId: 'G-Z32N45T1TR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyLn24K0oaaZkTIpp3lsmmkYA0EZrrjTY',
    appId: '1:491367868510:android:a0794edd3ff81ca98c6ccf',
    messagingSenderId: '491367868510',
    projectId: 'todo-app-df164',
    storageBucket: 'todo-app-df164.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-amG1E7WTi2dIS-pkMPGGlHMj682v3Z4',
    appId: '1:491367868510:ios:e77d172acd80391b8c6ccf',
    messagingSenderId: '491367868510',
    projectId: 'todo-app-df164',
    storageBucket: 'todo-app-df164.appspot.com',
    iosBundleId: 'com.example.newTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-amG1E7WTi2dIS-pkMPGGlHMj682v3Z4',
    appId: '1:491367868510:ios:c9403f37de3f26078c6ccf',
    messagingSenderId: '491367868510',
    projectId: 'todo-app-df164',
    storageBucket: 'todo-app-df164.appspot.com',
    iosBundleId: 'com.example.newTodo.RunnerTests',
  );
}
